import { describe, expect, it } from "vitest";
import { readMarkdownFile } from "../../src/fs/markdown.js";
import {
  loadTemplate,
  templatePath,
  defaultTemplateRoot,
} from "../../src/templates/index.js";

function requireFrontmatterObject(
  raw: unknown,
):
  | { ok: true; value: Record<string, unknown> }
  | { ok: false; reason: string } {
  if (typeof raw !== "object" || raw === null) {
    return { ok: false, reason: "frontmatter must be an object" };
  }
  return { ok: true, value: raw as Record<string, unknown> };
}

describe("project template integrity", () => {
  it("AGENTS.md exists and contains required sections and markers", async () => {
    const r = await loadTemplate("AGENTS.md");
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value).toContain("## Code Style");
    expect(r.value).toContain("## Codebase Map");
    expect(r.value).toContain("<!-- AUTO-GENERATED BY savepoint audit");
    expect(r.value).toContain("Never run `savepoint` commands");
  });

  it("router.md exists and contains agent instructions and read-order guidance", async () => {
    const r = await loadTemplate(".savepoint/router.md");
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value).toContain("<!-- AGENT:");
    expect(r.value).toContain("## Read order on every session");
    expect(r.value).toContain("## Current state");
    expect(r.value).toContain("## State → next action");
  });

  it("PRD.md has project-prd frontmatter and required headings", async () => {
    const path = templatePath(".savepoint/PRD.md", defaultTemplateRoot());
    const r = await readMarkdownFile(path, requireFrontmatterObject);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.frontmatter.type).toBe("project-prd");
    expect(r.value.body).toContain("## What it is");
    expect(r.value.body).toContain("## Why");
  });

  it("Design.md has project-design frontmatter and required headings", async () => {
    const path = templatePath(".savepoint/Design.md", defaultTemplateRoot());
    const r = await readMarkdownFile(path, requireFrontmatterObject);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.frontmatter.type).toBe("project-design");
    expect(r.value.body).toContain("## 1. Architecture model");
    expect(r.value.body).toContain("## 2. Directory layout");
  });

  it("config.yml exists and contains required top-level keys", async () => {
    const r = await loadTemplate(".savepoint/config.yml");
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value).toContain("quality_gates:");
    expect(r.value).toContain("audit:");
    expect(r.value).toContain("theme:");
  });

  it("visual-identity.md has visual-identity frontmatter and design sections", async () => {
    const path = templatePath(
      ".savepoint/visual-identity.md",
      defaultTemplateRoot(),
    );
    const r = await readMarkdownFile(path, requireFrontmatterObject);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.frontmatter.type).toBe("visual-identity");
    expect(r.value.body).toContain("## Palette");
    expect(r.value.body).toContain("## Typography");
  });
});
